version: '3'
services:
  server:
    build: rails-dockerfile
    volumes:
      - ./server:/work:cached
    ports:
      - 3000:3000
    depends_on:
      - pgsql
    tty: true
    working_dir: /work
  pgsql:
    image: postgres:10-alpine
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: develop
      POSTGRES_DATABASE: develop
    ports:
      - 5432:5432
